package cli

import (
	"context"
	"errors"
)

type ExitError struct {
	Code int
	Err  error
}

func (e *ExitError) Error() string { return e.Err.Error() }
func (e *ExitError) Unwrap() error { return e.Err }

func exitError(code int, err error) error {
	if err == nil {
		return nil
	}
	return &ExitError{Code: code, Err: err}
}

func ExitCode(err error) int {
	if err == nil {
		return 0
	}
	if errors.Is(err, context.Canceled) {
		return 130
	}
	var target *ExitError
	if errors.As(err, &target) {
		return target.Code
	}
	// Errors generated by Cobra before RunE (unknown commands, invalid
	// arguments) are usage errors. Runtime errors are wrapped below.
	return 2
}
